### ISSUE TITLE
Lag Issue

### ISSUE THREAD

**Issue by brilang** [cfjedimaster/IdleFleet#7]
When you have thousands of ships and click Send Ship(s), the web browser feels like it crashes for a few seconds while all ships are sent.

The auto-send fleets feature somewhat mitigates this issue, but I think that the more fleets one has, the more often auto-send should fire.

**Comment by cfjedimaster** [comment]
Should be fixed now. Note that it runs an event every second, so at like 500k ships, it will probaby break. 5k should be fine.
